### ISSUE TITLE
Morrowind code patch and MGE XE not loading

### ISSUE THREAD

**Issue by Theamazingwaffle** [Kezyma/Morrowind-Remastered#6]
Hi,

Really exited to play this list but I have encountered an issue during installation. I have carefully followed the instructions but I am obviously missing something that prevents me from completing the installation, seems like an incorrect file structure or something and I am really not experienced enough to solve the issue.

Any guidance would be greatly appreciated :)

When I try this step:
Select 'Morrowind Code Patch' in the application list (top right section of Mod Organizer).
Click 'Run'.

I get this error:
![Code patch error](https://github.com/Kezyma/Morrowind-Remastered/assets/161158093/aa3eeb79-294c-4ab7-9ec9-71267eaff24b)

I tried the next instruction and got something very similar, when I try this step:
Select 'MGE XE' in the application list (top right section of Mod Organizer).
Click 'Run'.

I get this error:
![MGE EXE error](https://github.com/Kezyma/Morrowind-Remastered/assets/161158093/37f368ef-5923-4066-8b78-bb799c1b9691)

In both instances the error box dissapears after a few seconds and nothing else seems to happen.

I also note that the Morrowind executable path is pointing to a non existent folder on a completely empty drive. My game is installed on drive E along with the modlist and wabbajack but the MO2 morrowind executable is pointing here:

D:\Repos\Morrowind-Remastered\Setup\Morrowind\Morrowind Launcher.exe

Apologies if I am just wasting time being a noob but I cant find any other more detailed installation instructions anywhere and I am the kind of pleb that needs a step by step video to be honest.

Cheers

**Comment by Kezyma** [comment]
Those aren't errors, that's just MO2 waiting for the applications to close. 

As for the exe, just point it to wherever you have Morrowind installed instead of the location where my copy of Morrowind is installed.

**Comment by Theamazingwaffle** [comment]
Hi thanks for looking at it but I am still confused here though and I realise now that I may have been unclear with my description of the issue.

These boxes are appearing immediately after I click run.

The guide indicates I need to get into the code patch and MGE XE and perform the steps in the instructions, like "apply chosen patches" but I can't get into either of them. 

These boxes appear as soon as I click run, dissapear after a few seconds but I don't ever get access to the code patch or MGE XE options.

**Comment by Kezyma** [comment]
They're expected, they show up while the applications are running. If the applications are closing unexpectedly right after launching, the boxes will disappear pretty quickly.

Considering it's happening with both MCP and MGE XE, I'd assume your AV is blocking them or something similar.

**Comment by Theamazingwaffle** [comment]
Tried a fresh install of the list and ran this step with AV disabled but got the same result.

Can I just check something on the pre installation instructions please?

"In the 'Modlist Installation Location' field, select an empty folder to install the modlist."

I created a folder called modlist in a seperate folder to my morrowind installation but on the same drive. Should the modlist folder be created in the morrowind folder?

**Comment by Kezyma** [comment]
It should never be created in the Morrowind folder, that'd cause Root Builder to break the game entirely!

**Comment by Theamazingwaffle** [comment]
Thanks for sticking with me on this, trying to nail down my issue for any others who are stonewalled.

I fear that some very basic file path errors on my part, due to a lack of proficiency using M02, may be the root cause of my inability to enjoy this list. Either when setting up the modded installation or when trying to get MO2 to do what it needs to do. I need more granular instructions, I need someone to assume I know nothing and cover every aspect of the installation, certainly a breakdown of the MO2 navigation. What are the chances of an install guide video?

Q1: So you are saying that it is correct for me to have created a separate folder for the modlist installation on the same drive that Morrowind was installed?

Q2: When you say: "Select Morrowind in the game list, if Morrowind isn't listed, scroll to the bottom, click 'Browse...' and locate your Morrowind folder"
What do you mean? 
Can you break that down with images?
Morrowind appears as an executable available within the run menu of MO2, does that mean I don't need to do anything?

Q3: does Wabbajack need a specific file path?

Q4: Does the fact that I have encountered this issue, even though I ran the executables with my AV disabled, indicate any other cause? 

Q5: Would you expect that disabling the AV while I run these steps eliminate the problem or do I need to make particular exemptions within the AV? Kind of looking for file paths if that is the case, like where are these executables located that I should exempt?

Q6: Aside from AV blocking, is there any other error on my part during the installation process that could cause the code patch and MGE EXE to fail GUI load?

I would immediately forgive you for giving up on me at this point but I REALLY want to get this list running.

**Comment by Kezyma** [comment]
1) Yes
2) You've found Morrowind in the list, but you probably need to change it to point at your install of Morrowind, as you've already mentioned earlier. There's two places you might need to change it as it defaults to the path I have the game on my PC.

- In MO2's settings, there's a tab called paths, one of them is the game path and should point to your Morrowind folder.
- In the executable list you've found already, you can edit the Morrowind and Morrowind Launcher ones to point to your install.

3) No
4) Not that I'm aware of
5) I'm not sure, I've never had an issue with AV myself, but it's the only issue I've ever heard someone having that would prevent both MCP and MGE XE from running.
6) Not that I'm aware of

You could try downloading and installing MCP and MGE XE manually to your game folder and seeing if they run at all. I would assume there's some issue with running them in general on your machine though, and not something specific to this list! People more familiar with troubleshooting those specific apps might be able to help more than I could though,

**Comment by Theamazingwaffle** [comment]
Fixed :)

As you suspected, it was an issue with some missing components preventing code patch and MGE XE from running on my system.

1- Yes I needed to update my Morrowind executable path as you instructed

2 - Morrowind code patch requires the following as per the readme:
If you get a MSVCR100.dll error, you need to download and install Visual C++ 2010 Redistributable Package (x86) 
https://www.microsoft.com/en-us/download/details.aspx?id=5555
It seems this dll error was not popping but it did when I tried a manual install.

3- MGE XE required that directx9.0c was updated, I got mine from here: https://www.filehorse.com/download-directx-9/
There was no warning for this during independent installation for me, but I did some digging online and updating this allowed the GUI to load.

Everything seems to work and I am so glad I have a modded install with voice acting as this is transformative.

Thank you so much.
