### ISSUE TITLE
Game stuck at start menu

### ISSUE THREAD

**Issue by nicobellic1** [Kezyma/Morrowind-Remastered#9]
When I load the game it gets frozen on the main menu, I can't move the cursor or do anithing else. I don't think I deviated for your install guide except I had the "Error code on running Morrowind in the Application List #7" problem which I resolved.  In case it may be relevant: my screen is 1920x1080 144 Hz and I always had a problem with Morrowind that doest recognize the discrete GPU (I already tried nvidia manager and the relevant windows settings).

**Comment by nicobellic1** [comment]
I solved the discrete gpu issue but the freezing problem remains

**Comment by nicobellic1** [comment]
Reinstalling in a different folder solved the problem.

**Comment by nicobellic1** [comment]
Reinstalling the game in a different folder solved the problem (reinstalling in the game in the same folder didn't help).

**Comment by sketchemL** [comment]
I am getting this issue as well, even though earlier today my game was working properly for hours. Upon starting up the list later in the day, for some reason my resolution was randomly changed to something like 1280x720. I changed it back to 1920x1080 using MGE XE in MO2, but now my menu screen is completely stuck and I am unable to use my mouse. I've tried tabbing out and tabbing back in, setting the game to windowed mode, and changing the resolution and refresh rate.

What exactly do you mean by "Reinstalling the game in a different folder"? Are you reinstalling the whole modlist, your Steam install of Morrowind, or the copy of Morrowind that running MOWJUI.exe created? I've tried the latter two options to no avail, and I am hesitant to reinstall the whole list as I don't see what would prevent this error from just happening again.

Any help here would be greatly appreciated.
